// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 portx.glb --types --transform 
Files: portx.glb [12.86MB] > /Users/kerim/Desktop/DFX Zero Trust/dataflowx-web/public/portx-transformed.glb [404.4KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Gövde_1: THREE.Mesh
    Gövde_2: THREE.Mesh
    Gövde_3: THREE.Mesh
    Gövde_4: THREE.Mesh
    Gövde_5: THREE.Mesh
    Gövde_6: THREE.Mesh
    Gövde_7: THREE.Mesh
    Gövde_8: THREE.Mesh
    Gövde_9: THREE.Mesh
    Gövde_10: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    USB_Metal: THREE.MeshStandardMaterial
    ['USB_Red Plastic']: THREE.MeshStandardMaterial
    ['USB_Metal Cooper']: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/portx-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[11.544, 126.782, -40.347]} rotation={[0, 0.014, -Math.PI / 2]} scale={0.364}>
        <mesh geometry={nodes.Gövde_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Gövde_2.geometry} material={materials.USB_Metal} />
        <mesh geometry={nodes.Gövde_3.geometry} material={materials['USB_Red Plastic']} />
        <mesh geometry={nodes.Gövde_4.geometry} material={materials['USB_Metal Cooper']} />
        <mesh geometry={nodes.Gövde_5.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Gövde_6.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Gövde_7.geometry} material={materials.PaletteMaterial005} />
        <mesh geometry={nodes.Gövde_8.geometry} material={materials.PaletteMaterial006} />
        <mesh geometry={nodes.Gövde_9.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Gövde_10.geometry} material={materials.PaletteMaterial002} />
      </group>
    </group>
  )
}

useGLTF.preload('/portx-transformed.glb')
